### ISSUE TITLE
Internet

### ISSUE THREAD

**Issue by nimaa77** [muhshahabipour/shahabipour.ir#8]
to chtori internet dari :)

vase ma am vpn befrest

**Comment by muhshahabipour** [comment]
ro network daneshgah sharif internet darim share nemishe :'(

**Comment by nimaa77** [comment]
manam ye vps dashtam rosh ye HTTP proxy bala avordam hey zarto zort ghat mishe

bebin onja kasi az proxy ina sar dar miare ? yekari konam in hey ghat nashe o ina ...
